title: Bedraad een zelfgemaakte knop of schakelaar
hero_image: images/banner.png
description: Hoe kan je een zelfgemaakte schakelaar aansluiten op een Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-09"
steps:
  - 
    title: Bedraad een zelfgemaakte knop of schakelaar
