title: Wiring for a crafted button or switch
hero_image: images/banner.png
description: crafted-switch-button-wiring description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-09"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
