title: Wire a crafted button or switch
hero_image: images/banner.png
description: How to wire a crafted switch to a Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-09"
steps:
  - 
    title: Wire a crafted button or switch
