---
title: Câbler un bouton ou un interrupteur artisanal
hero_image: images/banner.png
description: Comment câbler un commutateur artisanal à un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-09"
steps:
  - title: Câbler un bouton ou un interrupteur artisanal
